apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: docking
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: docking-v-v1
spec:
  rootResource: docking
  firstStage: register
  selfDriving: true
  stages:
    register:
      name: register
      provider: providers.stage.materialize
      stageSelector: ""
      config:
        baseUrl: http://symphony-service:8080/v1alpha2/
        user: admin
        password: ""  
      inputs:
        names:
        - "${{$trigger(truck-template, mock-truck:v1)}}"
      stageSelector: ${{$if($gt($trigger(driver.hours,0),8), notify, fuel)}}
      # ${{$if($gt($trigger(driver.hours,0),8), notify, "")}} if no next stage, empty string 
    notify:
      name: notify
      provider: providers.stage.http
      stageSelector: fuel
      config:
        name: test
		    url: "https://www.bing.com", # todo update when endpoint for azure logic app is available
		    method: "GET"
        successCodes: [200]
