FROM ubuntu:24.04
RUN apt-get update && apt-get install -y python3-pip python3-venv
RUN python3 -m venv /app/venv
COPY /docker/fuel-pump/fuel-pump.py /app
COPY /docker/fuel-pump/requirements.txt /app
RUN /app/venv/bin/pip install -r /app/requirements.txt
WORKDIR /app
ENTRYPOINT ["/app/venv/bin/python3", "-m", "uvicorn", "/app/fuel-pump:app", "--host", "0.0.0.0", "--port", "8000"]